### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by kieranklaassen** [nicklandgrebe/caprese#29]
When trying to render index page rails 5 tries to look for a template file.

```
[46a8dc46-766c-4abe-a27b-2ff0e35793c8] Started GET "/api/v1/merchants" for 127.0.0.1 at 2017-08-31 15:39:34 -0500
[46a8dc46-766c-4abe-a27b-2ff0e35793c8] Processing by API::V1::MerchantsController#index as HTML
[46a8dc46-766c-4abe-a27b-2ff0e35793c8]   Merchant Load (21.3ms)  SELECT  "merchants".* FROM "merchants" WHERE "merchants"."deleted_at" IS NULL AND "merchants"."api_login" = '' LIMIT 1
[46a8dc46-766c-4abe-a27b-2ff0e35793c8] Completed 500 Internal Server Error in 2083ms (ActiveRecord: 45.6ms)
[46a8dc46-766c-4abe-a27b-2ff0e35793c8] ** [Bugsnag] Notifying https://notify.bugsnag.com of ActionView::MissingTemplate
[46a8dc46-766c-4abe-a27b-2ff0e35793c8] 
ActionView::MissingTemplate - Missing template api/v1/merchants/index, api/v1/api/index, api/api/index, caprese//index with {:locale=>[:en], :formats=>[:html, :text, :js, :css, :ics, :csv, :vcf, :png, :jpeg, :gif, :bmp, :tiff, :svg, :mpeg, :xml, :rss, :atom, :yaml, :multipart_form, :url_encoded_form, :json, :pdf, :zip, :gzip], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :arb, :"inky-arb", :"inky-builder", :"inky-coffee", :"inky-erb", :"inky-html", :"inky-raw", :"inky-ruby", :inky, :haml, :"inky-haml"]}. Searched in:
  * "/Users/kieranklaassen/.rvm/gems/ruby-2.3.1@occasion/gems/bh-1.3.6/lib/bh/views"
  * "/Users/kieranklaassen/Dropbox (REC Sound Design BV)/rails/occasion/app/views"
  * "/Users/kieranklaassen/.rvm/gems/ruby-2.3.1@occasion/gems/activeadmin-1.1.0/app/views"
  * "/Users/kieranklaassen/.rvm/gems/ruby-2.3.1@occasion/gems/bootstrap-kaminari-views-0.0.5/app/views"
  * "/Users/kieranklaassen/.rvm/gems/ruby-2.3.1@occasion/gems/kaminari-0.16.3/app/views"
  * "/Users/kieranklaassen/.rvm/gems/ruby-2.3.1@occasion/gems/table-for-3.6.1/app/views"
  * "/Users/kieranklaassen/.rvm/gems/ruby-2.3.1@occasion/gems/swagger-ui_rails-0.1.7/app/views"
  * "/Users/kieranklaassen/.rvm/gems/ruby-2.3.1@occasion/gems/devise-4.3.0/app/views"
:
  spring (2.0.2) lib/spring/application.rb:287:in `block (2 levels) in shush_backtraces'
  actionview (5.1.3) lib/action_view/path_set.rb:46:in `find'
  actionview (5.1.3) lib/action_view/lookup_context.rb:116:in `find'
  actionview (5.1.3) lib/action_view/renderer/abstract_renderer.rb:18:in `find_template'
  actionview (5.1.3) lib/action_view/renderer/template_renderer.rb:38:in `determine_template'
  actionview (5.1.3) lib/action_view/renderer/template_renderer.rb:8:in `render'
  actionview (5.1.3) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (5.1.3) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (5.1.3) lib/action_view/rendering.rb:103:in `_render_template'
  actionpack (5.1.3) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (5.1.3) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (5.1.3) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
  actionpack (5.1.3) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
  actionpack (5.1.3) lib/abstract_controller/rendering.rb:24:in `render'
  actionpack (5.1.3) lib/action_controller/metal/rendering.rb:36:in `render'
  actionpack (5.1.3) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (5.1.3) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/kieranklaassen/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
  activesupport (5.1.3) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (5.1.3) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (5.1.3) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (5.1.3) lib/active_record/railties/controller_runtime.rb:29:in `cleanup_view_runtime'
  actionpack (5.1.3) lib/action_controller/metal/instrumentation.rb:43:in `render'
  remotipart (1.3.1) lib/remotipart/render_overrides.rb:16:in `render_with_remotipart'
  caprese (0.3.27) lib/caprese/controller/concerns/rendering.rb:31:in `render'
  app/controllers/concerns/api/authentication.rb:49:in `authenticate'
  activesupport (5.1.3) lib/active_support/callbacks.rb:413:in `block in make_lambda'
  activesupport (5.1.3) lib/active_support/callbacks.rb:178:in `block (2 levels) in halting_and_conditional'
  actionpack (5.1.3) lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
  activesupport (5.1.3) lib/active_support/callbacks.rb:179:in `block in halting_and_conditional'
  activesupport (5.1.3) lib/active_support/callbacks.rb:507:in `block in invoke_before'
  activesupport (5.1.3) lib/active_support/callbacks.rb:507:in `invoke_before'
  activesupport (5.1.3) lib/active_support/callbacks.rb:106:in `block in run_callbacks'
  caprese (0.3.27) lib/caprese/controller/concerns/errors.rb:44:in `enable_caprese_style_errors'
  activesupport (5.1.3) lib/active_support/callbacks.rb:117:in `block in run_callbacks'
  activesupport (5.1.3) lib/active_support/callbacks.rb:135:in `run_callbacks'
  actionpack (5.1.3) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (5.1.3) lib/action_controller/metal/rescue.rb:20:in `process_action'
  actionpack (5.1.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (5.1.3) lib/active_support/notifications.rb:166:in `block in instrument'
  activesupport (5.1.3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  activesupport (5.1.3) lib/active_support/notifications.rb:166:in `instrument'
  actionpack (5.1.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (5.1.3) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
  activerecord (5.1.3) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
  actionpack (5.1.3) lib/abstract_controller/base.rb:124:in `process'
  actionview (5.1.3) lib/action_view/rendering.rb:30:in `process'
  actionpack (5.1.3) lib/action_controller/metal.rb:189:in `dispatch'
  actionpack (5.1.3) lib/action_controller/metal.rb:253:in `dispatch'
  actionpack (5.1.3) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
  actionpack (5.1.3) lib/action_dispatch/routing/route_set.rb:31:in `serve'
  actionpack (5.1.3) lib/action_dispatch/journey/router.rb:46:in `block in serve'
  actionpack (5.1.3) lib/action_dispatch/journey/router.rb:33:in `serve'
  actionpack (5.1.3) lib/action_dispatch/routing/route_set.rb:834:in `call'
  recurring_select (2.0.0) app/middleware/recurring_select_middleware.rb:24:in `call'
  omniauth (1.6.1) lib/omniauth/strategy.rb:189:in `call!'
  omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
  rack (2.0.3) lib/rack/deflater.rb:34:in `call'
  remotipart (1.3.1) lib/remotipart/middleware.rb:32:in `call'
  warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
  warden (1.2.7) lib/warden/manager.rb:35:in `call'
  rack (2.0.3) lib/rack/etag.rb:25:in `call'
  rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
  rack (2.0.3) lib/rack/head.rb:12:in `call'
  rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
  rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
  actionpack (5.1.3) lib/action_dispatch/middleware/cookies.rb:613:in `call'
  actionpack (5.1.3) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
  activesupport (5.1.3) lib/active_support/callbacks.rb:97:in `run_callbacks'
  actionpack (5.1.3) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
  bugsnag (5.3.3) lib/bugsnag/rack.rb:34:in `call'
  better_errors (2.3.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.3.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.3.0) lib/better_errors/middleware.rb:57:in `call'
  actionpack (5.1.3) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
  actionpack (5.1.3) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  railties (5.1.3) lib/rails/rack/logger.rb:36:in `call_app'
  railties (5.1.3) lib/rails/rack/logger.rb:24:in `block in call'
  activesupport (5.1.3) lib/active_support/tagged_logging.rb:69:in `block in tagged'
  activesupport (5.1.3) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (5.1.3) lib/active_support/tagged_logging.rb:69:in `tagged'
  railties (5.1.3) lib/rails/rack/logger.rb:24:in `call'
  actionpack (5.1.3) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  request_store (1.3.2) lib/request_store/middleware.rb:9:in `call'
  actionpack (5.1.3) lib/action_dispatch/middleware/request_id.rb:25:in `call'
  rack (2.0.3) lib/rack/method_override.rb:22:in `call'
  rack (2.0.3) lib/rack/runtime.rb:22:in `call'
  activesupport (5.1.3) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
  actionpack (5.1.3) lib/action_dispatch/middleware/executor.rb:12:in `call'
  actionpack (5.1.3) lib/action_dispatch/middleware/static.rb:125:in `call'
  font_assets (0.1.14) lib/font_assets/middleware.rb:17:in `block in call'
  font_assets (0.1.14) lib/font_assets/middleware.rb:40:in `do_request'
  font_assets (0.1.14) lib/font_assets/middleware.rb:16:in `call'
  rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
  rack-cors (1.0.1) lib/rack/cors.rb:93:in `call'
  railties (5.1.3) lib/rails/engine.rb:522:in `call'
  rack-test (0.6.3) lib/rack/mock_session.rb:30:in `request'
  rack-test (0.6.3) lib/rack/test.rb:244:in `process_request'
  rack-test (0.6.3) lib/rack/test.rb:124:in `request'
  actionpack (5.1.3) lib/action_dispatch/testing/integration.rb:261:in `process'
  actionpack (5.1.3) lib/action_dispatch/testing/integration.rb:16:in `get'
  actionpack (5.1.3) lib/action_dispatch/testing/integration.rb:348:in `block (2 levels) in <module:Runner>'
  spec/support/api_helper.rb:30:in `auth_get'
  spec/requests/api/authentication_spec.rb:32:in `block (5 levels) in <module:API>'
  rspec-core (3.6.0) lib/rspec/core/example.rb:254:in `block in run'
  rspec-core (3.6.0) lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
  rspec-core (3.6.0) lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
  rspec-core (3.6.0) lib/rspec/core/hooks.rb:464:in `block in run'
  rspec-core (3.6.0) lib/rspec/core/hooks.rb:604:in `block in run_around_example_hooks_for'
  rspec-core (3.6.0) lib/rspec/core/example.rb:342:in `call'
  rspec-rails (3.6.1) lib/rspec/rails/adapters.rb:127:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
  rspec-core (3.6.0) lib/rspec/core/example.rb:447:in `instance_exec'
  rspec-core (3.6.0) lib/rspec/core/hooks.rb:375:in `execute_with'
  rspec-core (3.6.0) lib/rspec/core/hooks.rb:606:in `block (2 levels) in run_around_example_hooks_for'
  rspec-core (3.6.0) lib/rspec/core/example.rb:342:in `call'
   () Users/kieranklaassen/.rvm/gems/ruby-2.3.1@occasion/bundler/gems/rspec-retry-ed69ee3cfd85/lib/rspec/retry.rb:115:in `block in run'
   () Users/kieranklaassen/.rvm/gems/ruby-2.3.1@occasion/bundler/gems/rspec-retry-ed69ee3cfd85/lib/rspec/retry.rb:104:in `run'
   () Users/kieranklaassen/.rvm/gems/ruby-2.3.1@occasion/bundler/gems/rspec-retry-ed69ee3cfd85/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
   () Users/kieranklaassen/.rvm/gems/ruby-2.3.1@occasion/bundler/gems/rspec-retry-ed69ee3cfd85/lib/rspec/retry.rb:33:in `block (2 levels) in setup'
  rspec-core (3.6.0) lib/rspec/core/example.rb:447:in `instance_exec'
  rspec-core (3.6.0) lib/rspec/core/hooks.rb:375:in `execute_with'
  rspec-core (3.6.0) lib/rspec/core/hooks.rb:606:in `block (2 levels) in run_around_example_hooks_for'
  rspec-core (3.6.0) lib/rspec/core/example.rb:342:in `call'
  rspec-core (3.6.0) lib/rspec/core/hooks.rb:607:in `run_around_example_hooks_for'
  rspec-core (3.6.0) lib/rspec/core/hooks.rb:464:in `run'
  rspec-core (3.6.0) lib/rspec/core/example.rb:457:in `with_around_example_hooks'
  rspec-core (3.6.0) lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
  rspec-core (3.6.0) lib/rspec/core/example.rb:251:in `run'
  rspec-core (3.6.0) lib/rspec/core/example_group.rb:627:in `block in run_examples'
  rspec-core (3.6.0) lib/rspec/core/example_group.rb:623:in `run_examples'
  rspec-core (3.6.0) lib/rspec/core/example_group.rb:589:in `run'
  rspec-core (3.6.0) lib/rspec/core/example_group.rb:590:in `block in run'
  rspec-core (3.6.0) lib/rspec/core/example_group.rb:590:in `run'
  rspec-core (3.6.0) lib/rspec/core/example_group.rb:590:in `block in run'
  rspec-core (3.6.0) lib/rspec/core/example_group.rb:590:in `run'
  rspec-core (3.6.0) lib/rspec/core/example_group.rb:590:in `block in run'
  rspec-core (3.6.0) lib/rspec/core/example_group.rb:590:in `run'
  rspec-core (3.6.0) lib/rspec/core/runner.rb:118:in `block (3 levels) in run_specs'
  rspec-core (3.6.0) lib/rspec/core/runner.rb:118:in `block (2 levels) in run_specs'
  rspec-core (3.6.0) lib/rspec/core/configuration.rb:1894:in `with_suite_hooks'
  rspec-core (3.6.0) lib/rspec/core/runner.rb:113:in `block in run_specs'
  rspec-core (3.6.0) lib/rspec/core/reporter.rb:79:in `report'
  rspec-core (3.6.0) lib/rspec/core/runner.rb:112:in `run_specs'
  rspec-core (3.6.0) lib/rspec/core/runner.rb:87:in `run'
  rspec-core (3.6.0) lib/rspec/core/runner.rb:71:in `run'
  rspec-core (3.6.0) lib/rspec/core/runner.rb:45:in `invoke'
  rspec-core (3.6.0) exe/rspec:4:in `<top (required)>'
  activesupport (5.1.3) lib/active_support/dependencies.rb:286:in `block in load'
  activesupport (5.1.3) lib/active_support/dependencies.rb:258:in `load_dependency'
  activesupport (5.1.3) lib/active_support/dependencies.rb:286:in `load'
  spring-commands-rspec (1.0.4) lib/spring/commands/rspec.rb:18:in `call'
  spring (2.0.2) lib/spring/command_wrapper.rb:38:in `call'
  spring (2.0.2) lib/spring/application.rb:201:in `block in serve'
  spring (2.0.2) lib/spring/application.rb:171:in `serve'
  spring (2.0.2) lib/spring/application.rb:141:in `block in run'
  spring (2.0.2) lib/spring/application.rb:135:in `run'
  spring (2.0.2) lib/spring/application/boot.rb:19:in `<top (required)>'
  /Users/kieranklaassen/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

**Comment by nicklandgrebe** [comment]
Fixed
