### ISSUE TITLE
Can't render arbitrary json in a caprese controller

### ISSUE THREAD

**Issue by swrobel** [nicklandgrebe/caprese#47]
I have the following:
```ruby
rescue_from Stripe::StripeError do |e|
  render status: e.http_status, json: {
    errors: [{
      status: e.http_status,
      source: { pointer: '/data/attributes/pay_method' },
      title: e.json_body.dig(:error, :type),
      detail: e.json_body.dig(:error, :message)
    }]
  }
end
```

However, the controller fails with `RuntimeError · All models managed by Caprese must include Caprese::Record`

Note: I realize that I could rescue this in my PayMethod model and add to its errors there, but there are a variety of other scenarios where it would be useful to be able to render arbitrary json from within a Caprese controller.

**Comment by nicklandgrebe** [comment]
I think that there are two scenarios:

You have a parameter that is given to the controller outside of the resource document scope ('/data`), in which case, you can use:

```
rescue_from Stripe::StripeError do |e|
  render status: e.http_status, each_serializer: Caprese::Serializer::ErrorSerializer, json: [
    {
      field: 'attribute_name',
      code: e.json_body.dig(:error, :type),
      message: e.json_body.dig(:error, :message)
    }
  ]
end
```

Which would give the response:

```
{
  errors: [
    {
      source: { parameter: 'attribute_name' },
      code: [code],
      detail: [message]
    }
  ]
}
```

The other scenario is like you said, you handle this in the PayMethod model. As someone consuming this API, I have an easier time grasping `/data/relationships/pay_method/data` as an error source. Unfortunately, Caprese does not support the use of the JSONAPI `errors/title` field, which could be improved easily. So you can use `error/code` or add `error/title` to the library for your own purposes.

Caprese is designed from a resource-oriented perspective, so resources are converted through JSONAPI standard to a resource document, so the goal is to avoid rendering arbitrary json. If you want to render an error with `source: { pointer: '/data/...' }` it should be a resource. If you want to render any old param, use `source: { parameter: '....' }`.

**Comment by swrobel** [comment]
Thanks. What about a scenario where I just want to have a non-REST
controller action that returns arbitrary json?

**Comment by nicklandgrebe** [comment]
Use a Rails controller and route the action to it

**Comment by swrobel** [comment]
Hm, no luck with [your suggested code](https://github.com/nicklandgrebe/caprese/issues/47#issuecomment-375746216) (I did change `attribute_name` to a valid one for the model in question).

```
NoMethodError in Api::V1::User::PayMethodsController#create

undefined method `read_attribute_for_serialization' for #<Hash:0x00007fcf5bf3a390>
Extracted source (around line #381):

#379         send(attr)
#380       else
*381         object.read_attribute_for_serialization(attr)
#382       end
#383     end
#384 

Extracted source (around line #48):

#46 
#47         def id_for(serializer)
*48           serializer.read_attribute_for_serialization(Caprese.config.resource_primary_key).to_s
#49         end
#50       end
#51     end

Extracted source (around line #29):

#27         # {http://jsonapi.org/format/#document-resource-identifier-objects Resource Identifier Objects}
#28         def initialize(serializer, options)
*29           @id   = id_for(serializer)
#30           @type = type_for(serializer, options)
#31         end
#32 

Application Trace
app/controllers/concerns/rescue_from_stripe_error.rb:6:in `block (2 levels) in <module:RescueFromStripeError>'

Framework Trace
vendor/bundle/gems/active_model_serializers-0.10.7/lib/active_model/serializer.rb:381:in `read_attribute_for_serialization'
vendor/bundle/bundler/gems/caprese-1d8f10bbcdbf/lib/caprese/adapter/json_api/resource_identifier.rb:48:in `id_for'
vendor/bundle/bundler/gems/caprese-1d8f10bbcdbf/lib/caprese/adapter/json_api/resource_identifier.rb:29:in `initialize'
vendor/bundle/bundler/gems/caprese-1d8f10bbcdbf/lib/caprese/adapter/json_api.rb:234:in `new'
vendor/bundle/bundler/gems/caprese-1d8f10bbcdbf/lib/caprese/adapter/json_api.rb:234:in `process_resource'
vendor/bundle/bundler/gems/caprese-1d8f10bbcdbf/lib/caprese/adapter/json_api.rb:227:in `block in resource_objects_for'
vendor/bundle/gems/active_model_serializers-0.10.7/lib/active_model/serializer/collection_serializer.rb:5:in `each'
vendor/bundle/gems/active_model_serializers-0.10.7/lib/active_model/serializer/collection_serializer.rb:5:in `each'
vendor/bundle/bundler/gems/caprese-1d8f10bbcdbf/lib/caprese/adapter/json_api.rb:227:in `resource_objects_for'
vendor/bundle/bundler/gems/caprese-1d8f10bbcdbf/lib/caprese/adapter/json_api.rb:72:in `success_document'
vendor/bundle/bundler/gems/caprese-1d8f10bbcdbf/lib/caprese/adapter/json_api.rb:41:in `serializable_hash'
vendor/bundle/gems/active_model_serializers-0.10.7/lib/active_model_serializers/adapter/base.rb:59:in `as_json'
```

**Comment by swrobel** [comment]
Closing this, as I just ended up adding to model.errors.base. Thanks for your help troubleshooting!
